// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// score_test_stat_meta
Rcpp::List score_test_stat_meta(const Rcpp::List& X_list, const Rcpp::Nullable<Rcpp::List>& cluster_list, const Rcpp::List& col_index_list, const Rcpp::List& Y_R_list, const Rcpp::List& Y_I_list, const arma::uvec& X_par_index, const unsigned int n_par_interest_beta, const std::string& meta_method);
RcppExport SEXP _MetaQCAT_score_test_stat_meta(SEXP X_listSEXP, SEXP cluster_listSEXP, SEXP col_index_listSEXP, SEXP Y_R_listSEXP, SEXP Y_I_listSEXP, SEXP X_par_indexSEXP, SEXP n_par_interest_betaSEXP, SEXP meta_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List>& >::type cluster_list(cluster_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type col_index_list(col_index_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y_R_list(Y_R_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y_I_list(Y_I_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type X_par_index(X_par_indexSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_par_interest_beta(n_par_interest_betaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type meta_method(meta_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(score_test_stat_meta(X_list, cluster_list, col_index_list, Y_R_list, Y_I_list, X_par_index, n_par_interest_beta, meta_method));
    return rcpp_result_gen;
END_RCPP
}
// resample_pvalue
double resample_pvalue(const Rcpp::List& X_list, const Rcpp::Nullable<Rcpp::List>& cluster_id_list, const Rcpp::List& col_index_list, const Rcpp::List& Y_R_list, const Rcpp::List& Y_I_list, const arma::uvec& X_par_index, const double score_stat_meta, const int n_par_interest_beta, const unsigned int& n_replicates, const std::string& meta_method, const Rcpp::Nullable<Rcpp::String>& permute_strata);
RcppExport SEXP _MetaQCAT_resample_pvalue(SEXP X_listSEXP, SEXP cluster_id_listSEXP, SEXP col_index_listSEXP, SEXP Y_R_listSEXP, SEXP Y_I_listSEXP, SEXP X_par_indexSEXP, SEXP score_stat_metaSEXP, SEXP n_par_interest_betaSEXP, SEXP n_replicatesSEXP, SEXP meta_methodSEXP, SEXP permute_strataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List>& >::type cluster_id_list(cluster_id_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type col_index_list(col_index_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y_R_list(Y_R_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y_I_list(Y_I_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type X_par_index(X_par_indexSEXP);
    Rcpp::traits::input_parameter< const double >::type score_stat_meta(score_stat_metaSEXP);
    Rcpp::traits::input_parameter< const int >::type n_par_interest_beta(n_par_interest_betaSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type n_replicates(n_replicatesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type meta_method(meta_methodSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::String>& >::type permute_strata(permute_strataSEXP);
    rcpp_result_gen = Rcpp::wrap(resample_pvalue(X_list, cluster_id_list, col_index_list, Y_R_list, Y_I_list, X_par_index, score_stat_meta, n_par_interest_beta, n_replicates, meta_method, permute_strata));
    return rcpp_result_gen;
END_RCPP
}
// score_test_stat_QCAT_meta
Rcpp::List score_test_stat_QCAT_meta(const Rcpp::List& X_list, const Rcpp::Nullable<Rcpp::List>& cluster_list, const Rcpp::List& col_index_list, const Rcpp::List& Y_list, const Rcpp::List& coef_List, const arma::vec& X_par_index, const unsigned int n_par_interest_beta, const std::string& meta_method);
RcppExport SEXP _MetaQCAT_score_test_stat_QCAT_meta(SEXP X_listSEXP, SEXP cluster_listSEXP, SEXP col_index_listSEXP, SEXP Y_listSEXP, SEXP coef_ListSEXP, SEXP X_par_indexSEXP, SEXP n_par_interest_betaSEXP, SEXP meta_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List>& >::type cluster_list(cluster_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type col_index_list(col_index_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y_list(Y_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type coef_List(coef_ListSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type X_par_index(X_par_indexSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_par_interest_beta(n_par_interest_betaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type meta_method(meta_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(score_test_stat_QCAT_meta(X_list, cluster_list, col_index_list, Y_list, coef_List, X_par_index, n_par_interest_beta, meta_method));
    return rcpp_result_gen;
END_RCPP
}
// resample_QCAT_pvalue
double resample_QCAT_pvalue(const Rcpp::List& X_list, const Rcpp::Nullable<Rcpp::List>& cluster_list, const Rcpp::List& col_index_list, const Rcpp::List& Y_list, const Rcpp::List& coef_List, const arma::vec& X_par_index, const double score_stat_meta, const unsigned int n_par_interest_beta, const unsigned int n_perm, const std::string& meta_method, const Rcpp::Nullable<Rcpp::String>& permute_strata);
RcppExport SEXP _MetaQCAT_resample_QCAT_pvalue(SEXP X_listSEXP, SEXP cluster_listSEXP, SEXP col_index_listSEXP, SEXP Y_listSEXP, SEXP coef_ListSEXP, SEXP X_par_indexSEXP, SEXP score_stat_metaSEXP, SEXP n_par_interest_betaSEXP, SEXP n_permSEXP, SEXP meta_methodSEXP, SEXP permute_strataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List>& >::type cluster_list(cluster_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type col_index_list(col_index_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y_list(Y_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type coef_List(coef_ListSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type X_par_index(X_par_indexSEXP);
    Rcpp::traits::input_parameter< const double >::type score_stat_meta(score_stat_metaSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_par_interest_beta(n_par_interest_betaSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type meta_method(meta_methodSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::String>& >::type permute_strata(permute_strataSEXP);
    rcpp_result_gen = Rcpp::wrap(resample_QCAT_pvalue(X_list, cluster_list, col_index_list, Y_list, coef_List, X_par_index, score_stat_meta, n_par_interest_beta, n_perm, meta_method, permute_strata));
    return rcpp_result_gen;
END_RCPP
}
// score_test_stat_zero_meta
Rcpp::List score_test_stat_zero_meta(const Rcpp::List& Z_list, const Rcpp::Nullable<Rcpp::List>& cluster_list, const Rcpp::List& col_index_list, const Rcpp::List& Y_bin_list, const Rcpp::List& coef_List, const arma::vec& Z_par_index, const unsigned int n_par_interest_alpha, const std::string& meta_method);
RcppExport SEXP _MetaQCAT_score_test_stat_zero_meta(SEXP Z_listSEXP, SEXP cluster_listSEXP, SEXP col_index_listSEXP, SEXP Y_bin_listSEXP, SEXP coef_ListSEXP, SEXP Z_par_indexSEXP, SEXP n_par_interest_alphaSEXP, SEXP meta_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Z_list(Z_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List>& >::type cluster_list(cluster_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type col_index_list(col_index_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y_bin_list(Y_bin_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type coef_List(coef_ListSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z_par_index(Z_par_indexSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_par_interest_alpha(n_par_interest_alphaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type meta_method(meta_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(score_test_stat_zero_meta(Z_list, cluster_list, col_index_list, Y_bin_list, coef_List, Z_par_index, n_par_interest_alpha, meta_method));
    return rcpp_result_gen;
END_RCPP
}
// resample_zero_pvalue
double resample_zero_pvalue(const Rcpp::List& Z_list, const Rcpp::Nullable<Rcpp::List>& cluster_list, const Rcpp::List& col_index_list, const Rcpp::List& Y_bin_list, const Rcpp::List& coef_List, const arma::vec& Z_par_index, const double score_stat_meta, const unsigned int n_par_interest_alpha, const unsigned int n_perm, const std::string& meta_method, const Rcpp::Nullable<Rcpp::String>& permute_strata);
RcppExport SEXP _MetaQCAT_resample_zero_pvalue(SEXP Z_listSEXP, SEXP cluster_listSEXP, SEXP col_index_listSEXP, SEXP Y_bin_listSEXP, SEXP coef_ListSEXP, SEXP Z_par_indexSEXP, SEXP score_stat_metaSEXP, SEXP n_par_interest_alphaSEXP, SEXP n_permSEXP, SEXP meta_methodSEXP, SEXP permute_strataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Z_list(Z_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::List>& >::type cluster_list(cluster_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type col_index_list(col_index_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y_bin_list(Y_bin_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type coef_List(coef_ListSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z_par_index(Z_par_indexSEXP);
    Rcpp::traits::input_parameter< const double >::type score_stat_meta(score_stat_metaSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_par_interest_alpha(n_par_interest_alphaSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type meta_method(meta_methodSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::String>& >::type permute_strata(permute_strataSEXP);
    rcpp_result_gen = Rcpp::wrap(resample_zero_pvalue(Z_list, cluster_list, col_index_list, Y_bin_list, coef_List, Z_par_index, score_stat_meta, n_par_interest_alpha, n_perm, meta_method, permute_strata));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MetaQCAT_score_test_stat_meta", (DL_FUNC) &_MetaQCAT_score_test_stat_meta, 8},
    {"_MetaQCAT_resample_pvalue", (DL_FUNC) &_MetaQCAT_resample_pvalue, 11},
    {"_MetaQCAT_score_test_stat_QCAT_meta", (DL_FUNC) &_MetaQCAT_score_test_stat_QCAT_meta, 8},
    {"_MetaQCAT_resample_QCAT_pvalue", (DL_FUNC) &_MetaQCAT_resample_QCAT_pvalue, 11},
    {"_MetaQCAT_score_test_stat_zero_meta", (DL_FUNC) &_MetaQCAT_score_test_stat_zero_meta, 8},
    {"_MetaQCAT_resample_zero_pvalue", (DL_FUNC) &_MetaQCAT_resample_zero_pvalue, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_MetaQCAT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
