# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

score_test_stat_meta <- function(X_list, cluster_list, col_index_list, Y_R_list, Y_I_list, X_par_index, n_par_interest_beta, meta_method) {
    .Call(`_MetaQCAT_score_test_stat_meta`, X_list, cluster_list, col_index_list, Y_R_list, Y_I_list, X_par_index, n_par_interest_beta, meta_method)
}

resample_pvalue <- function(X_list, cluster_id_list, col_index_list, Y_R_list, Y_I_list, X_par_index, score_stat_meta, n_par_interest_beta, n_replicates, meta_method, permute_strata) {
    .Call(`_MetaQCAT_resample_pvalue`, X_list, cluster_id_list, col_index_list, Y_R_list, Y_I_list, X_par_index, score_stat_meta, n_par_interest_beta, n_replicates, meta_method, permute_strata)
}

score_test_stat_QCAT_meta <- function(X_list, cluster_list, col_index_list, Y_list, coef_List, X_par_index, n_par_interest_beta, meta_method) {
    .Call(`_MetaQCAT_score_test_stat_QCAT_meta`, X_list, cluster_list, col_index_list, Y_list, coef_List, X_par_index, n_par_interest_beta, meta_method)
}

resample_QCAT_pvalue <- function(X_list, cluster_list, col_index_list, Y_list, coef_List, X_par_index, score_stat_meta, n_par_interest_beta, n_perm, meta_method, permute_strata) {
    .Call(`_MetaQCAT_resample_QCAT_pvalue`, X_list, cluster_list, col_index_list, Y_list, coef_List, X_par_index, score_stat_meta, n_par_interest_beta, n_perm, meta_method, permute_strata)
}

score_test_stat_zero_meta <- function(Z_list, cluster_list, col_index_list, Y_bin_list, coef_List, Z_par_index, n_par_interest_alpha, meta_method) {
    .Call(`_MetaQCAT_score_test_stat_zero_meta`, Z_list, cluster_list, col_index_list, Y_bin_list, coef_List, Z_par_index, n_par_interest_alpha, meta_method)
}

resample_zero_pvalue <- function(Z_list, cluster_list, col_index_list, Y_bin_list, coef_List, Z_par_index, score_stat_meta, n_par_interest_alpha, n_perm, meta_method, permute_strata) {
    .Call(`_MetaQCAT_resample_zero_pvalue`, Z_list, cluster_list, col_index_list, Y_bin_list, coef_List, Z_par_index, score_stat_meta, n_par_interest_alpha, n_perm, meta_method, permute_strata)
}

